# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('count', models.IntegerField()),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
