language: python
sudo: required
dist: xenial
python: "3.7"

env:
  - AWS_ACCESS_KEY_ID='' AWS_SECRET_ACCESS_KEY='' AWS_STORAGE_BUCKET_NAME='' SECRET_KEY='dont-tell-eve' SSO_SECRET_KEY='dont-tell-eve' HORAS_DEFAULT_TZ='America/Puerto_Rico' TWITTER_API_KEY='' TWITTER_API_SECRET='' TWITTER_ACCESS_TOKEN='' TWITTER_ACCESS_TOKEN_SECRET=''
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run black --check .
  - pipenv run flake8 horas --ignore=E501
  - pipenv check
  - pipenv run python manage.py test --configuration=Testing --verbosity=3 --noinput
