version: '3'
services:
  db:
    image: postgres
    container_name: horas_db

  web:
    container_name: horas
    build: .
    command: serve
    env_file:
      - .env
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
