# Generated by Django 2.0.13 on 2019-06-22 18:48

import django.db.models.deletion
import django.utils.timezone
import django_fsm
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    apps.core.models.DateTimeCreatedField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "date_modified",
                    apps.core.models.DateTimeModifiedField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("format", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField(blank=True)),
                ("datetime", models.DateTimeField()),
                ("state", django_fsm.FSMField(default="available", max_length=50)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "protege",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proteges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-datetime",)},
        )
    ]
