# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 04:47
from __future__ import unicode_literals

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_states.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', apps.core.models.DateTimeCreatedField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('date_modified', apps.core.models.DateTimeModifiedField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('datetime', models.DateTimeField()),
                ('state', django_states.fields.StateField(db_index=True, default=b'available', max_length=100)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to=settings.AUTH_USER_MODEL)),
                ('protege', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proteges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='MeetingStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_states.fields.StateField(default=b'transition_initiated', max_length=100, verbose_name='state id')),
                ('from_state', models.CharField(choices=[(b'available', 'Available'), (b'confirmed', 'Confirmed'), (b'reserved', 'Reserved'), (b'deleted', 'Deleted'), (b'unused', 'Un-used'), (b'cancelled', 'Cancelled')], max_length=100)),
                ('to_state', models.CharField(choices=[(b'available', 'Available'), (b'confirmed', 'Confirmed'), (b'reserved', 'Reserved'), (b'deleted', 'Deleted'), (b'unused', 'Un-used'), (b'cancelled', 'Cancelled')], max_length=100)),
                ('serialized_kwargs', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='transition started at')),
                ('on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='meetings.Meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meeting transition',
            },
        ),
    ]
