# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-23 19:13
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [("meetings", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="state",
            field=django_fsm.FSMField(default="available", max_length=50),
        )
    ]
